doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
            carbon_immutable: \Carbon\Doctrine\DateTimeImmutableType
            carbon: \Carbon\Doctrine\DateTimeType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: 'mariadb-10.8.2'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Company:
                alias: App\Company
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Company/Infrastructure/ORM/Mapping'
                prefix: 'App\Company\Domain\Model'
            App\User:
                alias: User
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Infrastructure/ORM/Mapping'
                prefix: 'App\User\Domain\Model'
            App\Season:
                alias: Season
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Season/Infrastructure/ORM/Mapping'
                prefix: 'App\Season\Domain\Model'
            App\Security:
                alias: Security
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Security/Infrastructure/ORM/Mapping'
                prefix: 'App\Security\Domain\Model'
            App\Shared\Domain\ValueObject:
                alias: ValueObject
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/ORM/Mapping'
                prefix: 'App\Shared\Domain\ValueObject'
            App\Transaction:
                alias: Transaction
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Transaction/Infrastructure/ORM/Mapping'
                prefix: 'App\Transaction\Domain\Model'
