company:
    resource: ../../src/Company/Infrastructure/Controller/v1/
    type: annotation
    prefix: /api/v1
security:
    resource: ../../src/Security/Infrastructure/Controller/v1/
    type: annotation
    prefix: /api/v1
api_login:
    path: /api/v1/login
kernel:
    resource: ../../src/Kernel.php
    type: annotation
