framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - doctrine_transaction
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            async_failed: 'doctrine://default?queue_name=async_failed'
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: async_failed
            # Uncomment this and comment the line above for testing
            # async: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Shared\Application\Command\Command': sync
            'App\Shared\Application\Query\Query': sync
            'App\Shared\Domain\Event\DomainEvent': async
